### ISSUE TITLE
Image can't render using renderer.py

### ISSUE THREAD

**Issue by ebbsanchez** [dragonwocky/dragonwocky.github.io#1]
Hi, I'm trying to render notion content, too.
using your renderer but I can't render image.
I haven't really understood renderer.py but got not much time(and my python skills not good enough..)
wonder if you can help me out?

### view.py (highlighting the important part with '**')
```
def index(request):
    page, client = get_blog()

    renderer = HTMLRenderer(client)
    if len(HTMLRenderer.output) > 0:
            renderer.cleanup()
    **rendered_result = renderer.render_page(page)**
    **output = HTMLRenderer.output**
    print(len(output))
    title = page.title
    context = {
        'page': page,
        'title': title,
        'rendered': rendered_result,
        **'output': output,**
    }
    return render(request, 'blog/index.html', context)

```
### index.html
```
{{page.title}}<br>
{% for child in output %}
    {{child.content |safe}}
    <br>
{% endfor %}

```
### Notion:
<img width="584" alt="螢幕快照 2020-06-29 上午11 12 26" src="https://user-images.githubusercontent.com/8842298/85969196-8950f180-b9f9-11ea-8f41-2d1f5da78dca.png">

### Web
![螢幕快照 2020-06-29 上午11 12 56](https://user-images.githubusercontent.com/8842298/85969203-8e15a580-b9f9-11ea-8637-68659362b2ff.png)

**Comment by dragonwocky** [comment]
could you show me the raw HTML it generates? are any errors thrown?

**Comment by ebbsanchez** [comment]
oh wait. restart the server and the image have been rendered!!!
might be some package haven't load properly.. I can't believe this trouble me whole night yesterday lol
thanks for this renderer!! nice work!

**Comment by dragonwocky** [comment]
great, glad it ended up working :)
